version: '3'

dotenv: ['.env']

env:
  DOCKER_BUILDKIT: "1"

tasks:

  default:
    cmds:
      - go run .
  single-test:
    cmds:
      - go test --count=1 -v {{.CLI_ARGS}}
      # task single-test -- ./emailing -run TestSendEmail
      # - go test --count=1 -v ./... -run {{.CLI_ARGS}}
      # task single-test -- TestName
